//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface OfferRequest
{
	name: string|null;
	fields: string[];
	skills: string[];
	gender: string;
	age: number|null;
	phone: string|null;
	email: string|null;
	lastWorked: string|null;
	coronaPassed: boolean;
	availableFrom: string|null;
	address: string|null;
	location: any;
	experience: number;
	radius: number;
	comment: string|null;
}
