//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Offer } from './Offer';
import { Field } from './Field';

export interface Offer_Field
{
	offerId: string;
	offer: Offer;
	fieldId: string;
	field: Field;
}
