//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { Offer_Field } from './Offer_Field';
import { Offer_Skill } from './Offer_Skill';

export interface Offer
{
	id: string;
	name: string|null;
	fields: Offer_Field[];
	skills: Offer_Skill[];
	gender: string;
	dateOfBirth: string;
	experience: string|null;
	phone: string|null;
	email: string|null;
	lastWorked: string|null;
	coronaPassed: boolean;
	availableFrom: string|null;
	address: string|null;
	radius: number;
	comment: string|null;
	entfernung: number;
}
