//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export interface Offer
{
	id: string;
	name: string|null;
	fields: any[];
	skills: any[];
	gender: string;
	dateOfBirth: string;
	phone: string|null;
	email: string|null;
	lastWorked: string|null;
	coronaPassed: boolean;
	availableFrom: string|null;
	address: string|null;
	radius: number;
	comment: string|null;
	entfernung: number;
}
